name: Model pipeline

on:
  push:
    branches:
      - main

jobs:
  model-pipeline:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.9'

    # - name: Install Requirements
    #   run: |
    #     pip install -r requirements.txt

    # - name: Configure AWS credentials
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   run: |
    #     aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    #     aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    #     aws configure set region auto

    - name: Copy .env file
      run: echo "${{ secrets.ENV_FILE }}" > .env

    # - name: Run DVC experiments
    #   run: dvc exp run

    # - name: DVC push
    #   run: dvc push

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Push changes to new branch
      id: push-branch
      env:
        GITHUB_TOKEN: ${{ secrets.CONFIGURED_GITHUB_TOKEN }}
      run: |
        echo {{ secrets.CONFIGURED_GITHUB_TOKEN }}
        echo {{ secrets.CONFIGURED_GITHUB_TOKEN }} | gh auth login --with-token
        BRANCH_NAME=run-exp-$(date +'%Y%m%d-%H%M')
        git checkout -b $BRANCH_NAME
        git add dvc.lock dvclive
        git commit -m "Run DVC Experiments for model pipeline"
        git push origin $BRANCH_NAME
        echo "::set-output name=branch_name::$BRANCH_NAME"
  
    - name: Create Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.CONFIGURED_GITHUB_TOKEN }}
      run: |
        BRANCH_NAME=${{ needs.model-pipeline.outputs.branch_name }}
        curl -u "github-actions[bot]:${{ secrets.CONFIGURED_GITHUB_TOKEN }}" \
        -d '{"title":"Run DVC Experiments for model pipeline","head":"'"$BRANCH_NAME"'","base":"prod"}' \
        https://api.github.com/repos/${{ github.repository }}/pulls
